# permissions for end users to edit wasmcloudapplications.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wasmcloudapplication-editor-role
rules:
- apiGroups:
  - core.wasmcloud.com
  resources:
  - wasmcloudapplications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.wasmcloud.com
  resources:
  - wasmcloudapplications/status
  verbs:
  - get
