# permissions for end users to view wasmcloudapplications.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wasmcloudapplication-viewer-role
rules:
- apiGroups:
  - core.wasmcloud.com
  resources:
  - wasmcloudapplications
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.wasmcloud.com
  resources:
  - wasmcloudapplications/status
  verbs:
  - get
